In [1]:
#p67-70
import numpy as np

In [2]:
a = np.array([0.3, 2.9, 4.0])
#指数関数
exp_a = np.exp(a)

In [3]:
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [4]:
#指数関数の和
sum_exp_a = np.sum(exp_a)

In [5]:
sum_exp_a

74.1221542101633

In [6]:
y = exp_a / sum_exp_a

In [7]:
#yの総和は1になる
y

array([0.01821127, 0.24519181, 0.73659691])

### ソフトマック関数のオーバーフロー対策

In [8]:
# p69
a = np.array([1010, 1000, 990])
#正しく計算されない
np.exp(a) / np.sum(np.exp(a))

/Users/kazuki/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/kazuki/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan, nan, nan])

In [10]:
c = np.max(a)
c

1010

In [11]:
a - c

array([  0, -10, -20])

In [12]:
np.exp(a - c) / np.sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])